# delete this if development is finished
# start
devel:
 cache:
   enabled: false
 webassets:
   bundle: false
   clean_on_startup: true
   minify: false
# end
webcam:
  stream: plugin/mrbeam/static/img/test.jpg
plugins:
  discovery:
    publicPort: 80
  mrbeam:
   current_profile_id: MrBeam2B
   dev:
     software_tier: DEV
     cloud_env: DEV
  netconnectd:
    socket: /var/run/netconnectd.sock
  softwareupdate:
    checks:
      octoprint:
        update_folder: /home/pi/OctoPrint
      pcf8575:
        checkout_folder: /home/pi/pcf8575
        type: git_commit
        update_script: '{folder}/update.sh'
      netconnectd-daemon:
        checkout_folder: /home/pi/netconnectd
        type: git_commit
        update_script: '{folder}/update.sh'
      mrbeam-ledstrips:
        checkout_folder: /home/pi/mrbeamledstrips
        type: git_commit
        update_script: '{folder}/update.sh'
      netconnectd:
        checkout_folder: /home/pi/OctoPrint-Netconnectd
        type: git_commit
        update_script: '{folder}/update.sh'
        restart: octoprint
server:
  commands:
    serverRestartCommand: sudo systemctl restart octoprint.service
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
events:
  enabled: true
  subscriptions:
  - command: mrbeam_ledstrips_cli Startup
    event: Startup
    type: system
  - command: mrbeam_ledstrips_cli ClientOpened
    event: ClientOpened
    type: system
  - command: mrbeam_ledstrips_cli ClientClosed
    event: ClientClosed
    type: system
  - command: mrbeam_ledstrips_cli Connected
    event: Connected
    type: system
  - command: mrbeam_ledstrips_cli Disconnected
    event: Disconnected
    type: system
  - command: mrbeam_ledstrips_cli Error
    event: Error
    type: system
  - command: mrbeam_ledstrips_cli Upload
    event: Upload
    type: system
  - command: mrbeam_ledstrips_cli PrintStarted
    event: PrintStarted
    type: system
  - command: mrbeam_ledstrips_cli PrintDone
    event: PrintDone
    type: system
  - command: mrbeam_ledstrips_cli PrintCancelled
    event: PrintCancelled
    type: system
  - command: mrbeam_ledstrips_cli PrintPaused
    event: PrintPaused
    type: system
  - command: mrbeam_ledstrips_cli PrintResumed
    event: PrintResumed
    type: system
  - command: mrbeam_ledstrips_cli SlicingStarted
    event: SlicingStarted
    type: system
  - command: mrbeam_ledstrips_cli SlicingDone
    event: SlicingDone
    type: system
  - command: mrbeam_ledstrips_cli SlicingCancelled
    event: SlicingCancelled
    type: system
  - command: mrbeam_ledstrips_cli SlicingFailed
    event: SlicingFailed
    type: system
  - command: mrbeam_ledstrips_cli SlicingProgress:{__data}
    event: SlicingProgress
    type: system
  - command: mrbeam_ledstrips_cli SettingsUpdated
    event: SettingsUpdated
    type: system
  - command: mrbeam_ledstrips_cli progress:{__data}
    event: PrintProgress
    type: system