# delete this if development is finished
# start
devel:
 cache:
   enabled: false
 webassets:
   bundle: false
   clean_on_startup: true
   minify: false
# end
webcam:
  stream: plugin/mrbeam/static/img/test.jpg
plugins:
  discovery:
    publicPort: 80
  mrbeam:
   current_profile_id: MrBeam2B
   dev:
     software_tier: DEV
     cloud_env: DEV
  netconnectd:
    socket: /var/run/netconnectd.sock
  softwareupdate:
    checks:
      octoprint:
        checkout_folder: /home/pi/OctoPrint
        stable_branch:
          branch: mrbeam2-stable
      mrbeam:
        current: <mrbeamhash>
      netconnectd:
        current: <netconnectdpluginhash>
      netconnectd-daemon:
        current: <netconnectddaemonhash>
      mrbeam-ledstrips:
        current: <mrbeamledstripshash>
      findmymrbeam:
        current: <findmymrbeamhash>
      pcf8575:
        current: <pcf8575hash>
server:
  commands:
    serverRestartCommand: sudo systemctl restart octoprint.service
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
