# delete this if development is finished
# start
devel:
 cache:
   enabled: false
 webassets:
   bundle: false
   clean_on_startup: true
   minify: false
# end
webcam:
  stream: plugin/mrbeam/static/img/test.jpg
plugins:
  discovery:
    publicPort: 80
  mrbeam:
   current_profile_id: MrBeam2B
   dev:
     software_tier: DEV
     cloud_env: DEV
  netconnectd:
    socket: /var/run/netconnectd.sock
  softwareupdate:
    checks:
      octoprint:
        update_folder: /home/pi/OctoPrint
      pcf8575:
        checkout_folder: /home/pi/pcf8575
        type: git_commit
        update_script: '{folder}/update.sh'
      netconnectd-daemon:
        checkout_folder: /home/pi/netconnectd
        type: git_commit
        update_script: '{folder}/update.sh'
      mrbeam-ledstrips:
        checkout_folder: /home/pi/mrbeamledstrips
        type: git_commit
        update_script: '{folder}/update.sh'
      netconnectd:
        checkout_folder: /home/pi/OctoPrint-Netconnectd
        type: git_commit
        update_script: '{folder}/update.sh'
        restart: octoprint
server:
  commands:
    serverRestartCommand: sudo systemctl restart octoprint.service
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
